### ISSUE TITLE
ability_key and custom_key not working correctly

### ISSUE THREAD

**Issue by kEv1nZ0** [letsmokee/ApexXPFarmer#11]
ability_key = q
custom_key1 = f
custom_key2 = w
i use notepad check it. its work. can type q,f,w.
but in game it noting working on.i think are the key press time interval?

**Comment by kEv1nZ0** [comment]
im stupid. cuz the key press time too short.so W cant walk. everything is all right.

**Comment by letsmokee** [comment]
w is already pressed by default

**Comment by kEv1nZ0** [comment]
> w is already pressed by default

thx to reply. but the Q key not working.  :(

**Comment by letsmokee** [comment]
What legend do you play? Legends that require ability to be charged for a time could not work as you need to hold q for a period of time and the script just press and release, not holding. For me it's working for Lifeline

**Comment by kEv1nZ0** [comment]
i try Loba and Pathfinder.it doesn't work.i ill try the Lifeline.

**Comment by kEv1nZ0** [comment]
> What legend do you play? Legends that require ability to be charged for a time could not work as you need to hold q for a period of time and the script just press and release, not holding. For me it's working for Lifeline

have been try Lifeline ,Q still not working 😕

**Comment by kEv1nZ0** [comment]
> What legend do you play? Legends that require ability to be charged for a time could not work as you need to hold q for a period of time and the script just press and release, not holding. For me it's working for Lifeline

have been try Lifeline ,Q still not working 😕

**Comment by letsmokee** [comment]
Get in game and let the game detect lower left corner, and open in background notepad to see if it writes the keys.

**Comment by kEv1nZ0** [comment]
> Get in game and let the game detect lower left corner, and open in background notepad to see if it writes the keys.

Yes, it wrote Q in notepad, but I don't know why it didn't work in the game.

**Comment by letsmokee** [comment]
How many fps do you got? Are fps capped? How are capped? Is Vsync active? Do you have gsync/freesync? ARe you running in windowed borderless?

**Comment by kEv1nZ0** [comment]
> How many fps do you got? Are fps capped? How are capped? Is Vsync active? Do you have gsync/freesync? ARe you running in windowed borderless?

I want to run the program for a long time with low power consumption, so I limit the game to 60fps. What is the minimum allowable fps?

I'm running in borderless.

**Comment by letsmokee** [comment]
I'm running with 25FPS capped with RTSS. Don't cap with vsync or in game limiter. Maybe it creates input lag.

**Comment by kEv1nZ0** [comment]
> I'm running with 25FPS capped with RTSS. Don't cap with vsync or in game limiter. Maybe it creates input lag.

Ok, I'll try it.

**Comment by kEv1nZ0** [comment]
> I'm running with 25FPS capped with RTSS. Don't cap with vsync or in game limiter. Maybe it creates input lag.

I deleted +fps_max limited Steam , and limited it to 25fps with RTSS, but I still can't use Q.

**Comment by letsmokee** [comment]
Something is on your end as script presses q. Are you sure ability set to q?

**Comment by kEv1nZ0** [comment]
> Something is on your end as script presses q. Are you sure ability set to q?

yep,im sure ability set to q. and it can wrote on notepad. except the q everything seems work great.

**Comment by letsmokee** [comment]
Have you fixed the issue?

**Comment by kEv1nZ0** [comment]
> Have you fixed the issue?

Yes, but I don't know what i do to fix it.

here is what step i tried.
1.remove -dev “+fps_max 60”on steam 
2.use RTSS limit fps to 25fps

i try those step it doesn't work in first time,but i restart the farmer few times it works great.
