### ISSUE TITLE
Not starting match by itself

### ISSUE THREAD

**Issue by forreals** [letsmokee/ApexXPFarmer#16]
I followed all the steps. After running the exe file, it automatically goes to the game but does not start the match. Any fix?

**Comment by letsmokee** [comment]
Is game in english language? Does the executable closes? Without more details and just "does not start the match" I cannot give a fix.

**Comment by forreals** [comment]
Yes, english. Executable does not close. After pressing enter on the executable, it automatically alt tabs to the game but it does not start the match its like after alt tabbing to the game it does not work.

**Comment by letsmokee** [comment]
1920x1080 borderless?

**Comment by forreals** [comment]
Fullscreen

**Comment by letsmokee** [comment]
Try borderless fullscreen. For me works just fine. Without more info I cannot help you

**Comment by forreals** [comment]
Great. Got all my accounts banned using this execution. Deleted them all and no more bans.
