### ISSUE TITLE
windows exe issue

### ISSUE THREAD

**Issue by oMaikeru** [letsmokee/ApexXPFarmer#4]
after running the exe the game opens and start without any issues but as soon as the game end the cmd closes itself and doesnt restart another game

**Comment by letsmokee** [comment]
can you start the exe in a batch? to see the error when this happens as I don't get this error
open cmd in directory of exe and type ApexFarmer.v1.2.3.exe or whatever name does it have

**Comment by oMaikeru** [comment]
Traceback (most recent call last):
  File "ApexFarmer.py", line 243, in <module>
ValueError: invalid literal for int() with base 10: '1\n\n246\n'
[6764] Failed to execute script 'ApexFarmer' due to unhandled exception!

**Comment by letsmokee** [comment]
It's regarding OCR and I'm working on it
If you want, use latest version which I am currently testing and just uploaded. Otherwise, if you don't care about to know EXP earned, please use v1.0.

**Comment by letsmokee** [comment]
I will close this. Test version v1.3 as I have updated the method and testing is doing good. Open another if you encounter another problem.
