### ISSUE TITLE
app randomly crashes after a game or two

### ISSUE THREAD

**Issue by xxxneo7** [letsmokee/ApexXPFarmer#6]
Traceback (most recent call last):
  File "ApexFarmer.py", line 293, in <module>
ValueError: invalid literal for int() with base 10: ''
[23316] Failed to execute script 'ApexFarmer' due to unhandled exception!

![image](https://github.com/letsmokee/ApexXPFarmer/assets/62401907/d9308508-15bb-44b0-9db7-2b65e2e864fe)

**Comment by letsmokee** [comment]
do you run the game in windowed borderless 1920x1080?

**Comment by xxxneo7** [comment]
![image](https://github.com/letsmokee/ApexXPFarmer/assets/62401907/3afa4bf3-482d-451e-b79c-fcbd0bdc4059)
latest version 1.5.1

**Comment by letsmokee** [comment]
can you activate debug mode and when this happens send me the photos and data file that you have in the folder with the executable please

**Comment by xxxneo7** [comment]
ok

**Comment by xxxneo7** [comment]
![saved_without_exp1](https://github.com/letsmokee/ApexXPFarmer/assets/62401907/620356f5-b28e-4683-a57e-c53f6b39918d)
![image](https://github.com/letsmokee/ApexXPFarmer/assets/62401907/7957ffbf-ee26-4e7a-a415-914f9f379d0c)

**Comment by letsmokee** [comment]
I understood the problem, put show_exp on 0 and wait until I patch this. It's because of the "1 boost applied" text which moves down a bit the exp gained.

**Comment by xxxneo7** [comment]
alr ty

**Comment by letsmokee** [comment]
fixed, please turn on debug and open from cmd when you test v1.5.2 as still errors can occur. If it does, post it here. In 24-48h I will close this otherwise

**Comment by xxxneo7** [comment]
everything now works as intended
