### ISSUE TITLE
Bot stuck on matchmaking

### ISSUE THREAD

**Issue by XxJustGabexX** [letsmokee/ApexXPFarmer#7]
Hi there whenever I run the bot and it’s in the lobby readied up it’s stuck on processing (map) forever. Is there any way to fix this?
![IMG_1021](https://github.com/letsmokee/ApexXPFarmer/assets/155209295/6850d3bc-b9d0-48a0-99ff-95b9c7fd6a4a)

**Comment by letsmokee** [comment]
From my point of view, not a problem of the bot. Probably internet problems or server side issues. Regarding servers, they are garbage and time to time this happens. The bot doesn't interact with something that would block communicating with the servers.
What could I do is to implement a restart if it's in active matchmaking for more than 5 minutes. 
My bot currently farming for 6 hours and got 54k xp so no problems.

**Comment by XxJustGabexX** [comment]
> From my point of view, not a problem of the bot. Probably internet problems or server side issues. Regarding servers, they are garbage and time to time this happens. The bot doesn't interact with something that would block communicating with the servers. What could I do is to implement a restart if it's in active matchmaking for more than 5 minutes. My bot currently farming for 6 hours and got 54k xp so no problems.

Oh ok Ty lol I was scared that maybe I was shadow banned or some shit
